# Generated by Django 3.2.1 on 2021-05-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
