# Generated by Django 3.2.1 on 2021-05-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210514_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='storage_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
